# 数据源配置
spring:
  application:
  name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.2.248
    port: 5672
    username: huike-site
    password: uZR7ZxEElsDOkwSi
    #虚拟host 可以不设置,使用server默认host
    #virtual-host
    listener:
      direct:
        retry:
          #开启重试
          enabled: true
          #重试3次
          max-attempts: 3
          #间隔时间 1s
          initial-interval: 1000
  redis:
    database: 255
    host: r-2ze3v6eo8gd1zrmr4h.redis.rds.aliyuncs.com      # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: V@ZR1&0Yms8%n#Sl0dmD             # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10          # 连接池中的最大空闲连接
        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0           # 连接池中的最小空闲连接
    timeout: 10004           # 连接超时时间（毫秒）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://rm-2ze7pw1263p789cvm.mysql.rds.aliyuncs.com/hk_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: huike_site
        password: hnbKumE1frNHCq73
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
